source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SSPageView_Example', :exclusive => true do
  pod 'SSPageViewController', :path => '../'
end

target 'SSPageView_Tests', :exclusive => true do
  pod 'SSPageViewController', :path => '../'
end
